name: Deploy postgresql api

on:
  push:
    branches: ["master"]

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: echo 'hello world ...'
      - run: ls -la
      - run: touch .env
      - run: echo 'DV_DATABASE_URL:'
      - run: echo ' '
      - run: docker build -t abrahamcast/pg-restapi .
      - run: docker images
